'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InstaDL_Generator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @charset &quot;UTF-8&quot;;
        '''
        '''/*!
        '''Animate.css - http://daneden.me/animate
        '''Licensed under the MIT license - http://opensource.org/licenses/MIT
        '''
        '''Copyright (c) 2015 Daniel Eden
        '''*/
        '''
        '''.animated {
        '''  -webkit-animation-duration: 1s;
        '''  animation-duration: 1s;
        '''  -webkit-animation-fill-mode: both;
        '''  animation-fill-mode: both;
        '''}
        '''.animated-fast {
        '''  -webkit-animation-duration: .5s;
        '''  animation-duration: .5s;
        '''  -webkit-animation-fill-mode: both;
        '''  animation-fill-mode: both;
        '''}
        '''
        '''.animated.infinite {
        '''  -webkit-ani [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property animate_css() As String
            Get
                Return ResourceManager.GetString("animate.css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @charset &quot;UTF-8&quot;;
        '''/*!
        ''' * Bootstrap v3.3.5 (http://getbootstrap.com)
        ''' * Copyright 2011-2015 Twitter, Inc.
        ''' * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        ''' */
        '''/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
        '''html {
        '''  font-family: sans-serif;
        '''  -ms-text-size-adjust: 100%;
        '''  -webkit-text-size-adjust: 100%;
        '''}
        '''
        '''body {
        '''  margin: 0;
        '''}
        '''
        '''article,
        '''aside,
        '''details,
        '''figcaption,
        '''figure,
        '''footer,
        '''header,
        '''hgroup,
        '''main,
        '''menu,
        '''nav,
        '''section,
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap_css() As String
            Get
                Return ResourceManager.GetString("bootstrap.css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        ''' * Bootstrap v3.3.5 (http://getbootstrap.com)
        ''' * Copyright 2011-2015 Twitter, Inc.
        ''' * Licensed under the MIT license
        ''' */
        '''if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;var b=a.fn.jquery.split(&quot; &quot;)[0].split(&quot;.&quot;);if(b[0]&lt;2&amp;&amp;b[1]&lt;9||1==b[0]&amp;&amp;9==b[1]&amp;&amp;b[2]&lt;1)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery version 1.9.1 or higher&quot;)}(jQuery),+function(a){&quot;use strict&quot;;function b(){var a=document.createElement(&quot;bootstrap&quot;),b={WebkitTrans [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap_min() As String
            Get
                Return ResourceManager.GetString("bootstrap_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 			&lt;/div&gt;
        '''		&lt;/div&gt;
        '''	&lt;/div&gt;
        '''	
        '''
        '''
        '''	&lt;/div&gt;
        '''
        '''	&lt;div class=&quot;gototop js-top&quot;&gt;
        '''		&lt;a href=&quot;#&quot; class=&quot;js-gotop&quot;&gt;&lt;i class=&quot;icon-arrow-up&quot;&gt;&lt;/i&gt;&lt;/a&gt;
        '''	&lt;/div&gt;
        '''	
        '''	&lt;!-- jQuery --&gt;
        '''	&lt;script src=&quot;js/jquery.min.js&quot;&gt;&lt;/script&gt;
        '''	&lt;!-- jQuery Easing --&gt;
        '''	&lt;script src=&quot;js/jquery.easing.1.3.js&quot;&gt;&lt;/script&gt;
        '''	&lt;!-- Bootstrap --&gt;
        '''	&lt;script src=&quot;js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        '''	&lt;!-- Waypoints --&gt;
        '''	&lt;script src=&quot;js/jquery.waypoints.min.js&quot;&gt;&lt;/script&gt;
        '''	&lt;!-- countTo --&gt;
        '''	&lt;script src=&quot;js/jquery.countTo.js&quot;&gt;&lt;/script&gt;
        '''	&lt;!-- Magnif [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BottomPart() As String
            Get
                Return ResourceManager.GetString("BottomPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property File() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("File", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 				&lt;div class=&quot;col-md-4 col-sm-4 animate-box&quot; data-animate-effect=&quot;fadeIn&quot;&gt;
        '''					&lt;div class=&quot;fh5co-staff&quot;&gt;
        '''						&lt;a href=&quot;/$FILEPATH/&quot;&gt;
        '''						&lt;img src=&quot;css/application.png&quot; alt=&quot;&quot; &gt;
        '''						&lt;h3&gt;$FILENAME&lt;/h3&gt;
        '''						&lt;p&gt;Application/File&lt;/p&gt;
        '''						&lt;/a&gt;
        '''					&lt;/div&gt;
        '''				&lt;/div&gt;.
        '''</summary>
        Friend ReadOnly Property FilePart() As String
            Get
                Return ResourceManager.GetString("FilePart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' * jQuery FlexSlider v2.6.0
        ''' * http://www.woothemes.com/flexslider/
        ''' *
        ''' * Copyright 2012 WooThemes
        ''' * Free to use under the GPLv2 and later license.
        ''' * http://www.gnu.org/licenses/gpl-2.0.html
        ''' *
        ''' * Contributing author: Tyler Smith (@mbmufffin)
        ''' *
        ''' */
        '''/* ====================================================================================================================
        ''' * FONT-FACE
        ''' * ============================================================================================================ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property flexslider_css() As String
            Get
                Return ResourceManager.GetString("flexslider.css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 				&lt;div class=&quot;col-md-4 col-sm-4 animate-box&quot; data-animate-effect=&quot;fadeIn&quot;&gt;
        '''					&lt;div class=&quot;fh5co-staff&quot;&gt;
        '''						&lt;a href=&quot;$PATHNAME/&quot;&gt;
        '''						&lt;img src=&quot;folder.png&quot; alt=&quot;&quot; &gt;
        '''						&lt;h3&gt;$FOLDERNAME&lt;/h3&gt;
        '''						&lt;p&gt;Folder/Directory&lt;/p&gt;
        '''						&lt;/a&gt;
        '''					&lt;/div&gt;
        '''				&lt;/div&gt;.
        '''</summary>
        Friend ReadOnly Property folderpart() As String
            Get
                Return ResourceManager.GetString("folderpart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @font-face {
        '''  font-family: &apos;icomoon&apos;;
        '''  src:  url(&apos;../fonts/icomoon/icomoon.eot?6iuir&apos;);
        '''  src:  url(&apos;../fonts/icomoon/icomoon.eot?6iuir#iefix&apos;) format(&apos;embedded-opentype&apos;),
        '''    url(&apos;../fonts/icomoon/icomoon.ttf?6iuir&apos;) format(&apos;truetype&apos;),
        '''    url(&apos;../fonts/icomoon/icomoon.woff?6iuir&apos;) format(&apos;woff&apos;),
        '''    url(&apos;../fonts/icomoon/icomoon.svg?6iuir#icomoon&apos;) format(&apos;svg&apos;);
        '''  font-weight: normal;
        '''  font-style: normal;
        '''}
        '''
        '''[class^=&quot;icon-&quot;], [class*=&quot; icon-&quot;] {
        '''  /* use !important to prevent issues wit [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property icomoon_css() As String
            Get
                Return ResourceManager.GetString("icomoon.css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instadl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instadl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instadlblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instadlblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ISO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ISO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (function (factory) {
        '''    if (typeof define === &apos;function&apos; &amp;&amp; define.amd) {
        '''        // AMD
        '''        define([&apos;jquery&apos;], factory);
        '''    } else if (typeof exports === &apos;object&apos;) {
        '''        // CommonJS
        '''        factory(require(&apos;jquery&apos;));
        '''    } else {
        '''        // Browser globals
        '''        factory(jQuery);
        '''    }
        '''}(function ($) {
        '''  var CountTo = function (element, options) {
        '''    this.$element = $(element);
        '''    this.options  = $.extend({}, CountTo.DEFAULTS, this.dataOptions(), options);
        '''    this.init();
        '''  };
        '''
        '''  CountTo.DE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_countTo() As String
            Get
                Return ResourceManager.GetString("jquery_countTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' * jQuery Easing v1.3 - http://gsgd.co.uk/sandbox/jquery/easing/
        ''' *
        ''' * Uses the built in easing capabilities added In jQuery 1.1
        ''' * to offer multiple easing options
        ''' *
        ''' * TERMS OF USE - jQuery Easing
        ''' * 
        ''' * Open source under the BSD License. 
        ''' * 
        ''' * Copyright Ã‚Â© 2008 George McGinley Smith
        ''' * All rights reserved.
        ''' * 
        ''' * Redistribution and use in source and binary forms, with or without modification, 
        ''' * are permitted provided that the following conditions are met:
        ''' * 
        ''' * Redistributions of source code m [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_easing_1_3() As String
            Get
                Return ResourceManager.GetString("jquery_easing_1_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! Magnific Popup - v0.9.9 - 2014-09-06
        '''* http://dimsemenov.com/plugins/magnific-popup/
        '''* Copyright (c) 2014 Dmitry Semenov; */
        '''(function(e){var t,n,i,o,r,a,s,l=&quot;Close&quot;,c=&quot;BeforeClose&quot;,d=&quot;AfterClose&quot;,u=&quot;BeforeAppend&quot;,p=&quot;MarkupParse&quot;,f=&quot;Open&quot;,m=&quot;Change&quot;,g=&quot;mfp&quot;,h=&quot;.&quot;+g,v=&quot;mfp-ready&quot;,C=&quot;mfp-removing&quot;,y=&quot;mfp-prevent-close&quot;,w=function(){},b=!!window.jQuery,I=e(window),x=function(e,n){t.ev.on(g+e+h,n)},k=function(t,n,i,o){var r=document.createElement(&quot;div&quot;);return r.className=&quot;mfp-&quot;+t,i&amp;&amp;(r.innerHTML=i),o?n&amp;&amp;n. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_magnific_popup_min() As String
            Get
                Return ResourceManager.GetString("jquery_magnific_popup_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
        '''!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.4&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_min() As String
            Get
                Return ResourceManager.GetString("jquery_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        '''Waypoints - 4.0.0
        '''Copyright Â© 2011-2015 Caleb Troughton
        '''Licensed under the MIT license.
        '''https://github.com/imakewebthings/waypoints/blog/master/licenses.txt
        '''*/
        '''!function(){&quot;use strict&quot;;function t(o){if(!o)throw new Error(&quot;No options passed to Waypoint constructor&quot;);if(!o.element)throw new Error(&quot;No element option passed to Waypoint constructor&quot;);if(!o.handler)throw new Error(&quot;No handler option passed to Waypoint constructor&quot;);this.key=&quot;waypoint-&quot;+e,this.options=t.Adapter.extend({},t.defaults,o),this.el [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_waypoints_min() As String
            Get
                Return ResourceManager.GetString("jquery_waypoints_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /* Magnific Popup CSS */
        '''.mfp-bg {
        '''  top: 0;
        '''  left: 0;
        '''  width: 100%;
        '''  height: 100%;
        '''  z-index: 1042;
        '''  overflow: hidden;
        '''  position: fixed;
        '''  background: #0b0b0b;
        '''  opacity: 0.8;
        '''  filter: alpha(opacity=80); }
        '''
        '''.mfp-wrap {
        '''  top: 0;
        '''  left: 0;
        '''  width: 100%;
        '''  height: 100%;
        '''  z-index: 1043;
        '''  position: fixed;
        '''  outline: none !important;
        '''  -webkit-backface-visibility: hidden; }
        '''
        '''.mfp-container {
        '''  text-align: center;
        '''  position: absolute;
        '''  width: 100%;
        '''  height: 100%;
        '''  left:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property magnific_popup_css() As String
            Get
                Return ResourceManager.GetString("magnific-popup.css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $(document).ready(function() {
        '''  // MagnificPopup
        '''	var magnifPopup = function() {
        '''		$(&apos;.image-popup&apos;).magnificPopup({
        '''			type: &apos;image&apos;,
        '''			removalDelay: 300,
        '''			mainClass: &apos;mfp-with-zoom&apos;,
        '''			gallery:{
        '''				enabled:true
        '''			},
        '''			zoom: {
        '''				enabled: true, // By default it&apos;s false, so don&apos;t forget to enable it
        '''
        '''				duration: 300, // duration of the effect, in milliseconds
        '''				easing: &apos;ease-in-out&apos;, // CSS transition easing function
        '''
        '''				// The &quot;opener&quot; function should return the element from which popup will  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property magnific_popup_options() As String
            Get
                Return ResourceManager.GetString("magnific_popup_options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ;(function () {
        '''	
        '''	&apos;use strict&apos;;
        '''
        '''	var mobileMenuOutsideClick = function() {
        '''
        '''		$(document).click(function (e) {
        '''	    var container = $(&quot;#fh5co-offcanvas, .js-fh5co-nav-toggle&quot;);
        '''	    if (!container.is(e.target) &amp;&amp; container.has(e.target).length === 0) {
        '''
        '''	    	if ( $(&apos;body&apos;).hasClass(&apos;offcanvas&apos;) ) {
        '''
        '''    			$(&apos;body&apos;).removeClass(&apos;offcanvas&apos;);
        '''    			$(&apos;.js-fh5co-nav-toggle&apos;).removeClass(&apos;active&apos;);
        '''				
        '''	    	}
        '''	    
        '''	    	
        '''	    }
        '''		});
        '''
        '''	};
        '''
        '''
        '''	var offcanvasMenu = function() {
        '''
        '''		$(&apos;#page&apos;).prepend(&apos;&lt;div i [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property main() As String
            Get
                Return ResourceManager.GetString("main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /* Modernizr 2.6.2 (Custom Build) | MIT &amp; BSD
        ''' * Build: http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inlines [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property modernizr_2_6_2_min() As String
            Get
                Return ResourceManager.GetString("modernizr_2_6_2_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MP4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MP4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''/*! Respond.js v1.4.2: min/max-width media query polyfill * Copyright 2013 Scott Jehl
        ''' * Licensed under https://github.com/scottjehl/Respond/blob/master/LICENSE-MIT
        ''' *  */
        '''
        '''!function(a){&quot;use strict&quot;;a.matchMedia=a.matchMedia||function(a){var b,c=a.documentElement,d=c.firstElementChild||c.firstChild,e=a.createElement(&quot;body&quot;),f=a.createElement(&quot;div&quot;);return f.id=&quot;mq-test-1&quot;,f.style.cssText=&quot;position:absolute;top:-100em&quot;,e.style.background=&quot;none&quot;,e.appendChild(f),function(a){return f.innerHTML=&apos;&amp;shy;&lt;style me [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property respond_min() As String
            Get
                Return ResourceManager.GetString("respond_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @font-face {
        '''  font-family: &apos;icomoon&apos;;
        '''  src: url(&quot;../fonts/icomoon/icomoon.eot?srf3rx&quot;);
        '''  src: url(&quot;../fonts/icomoon/icomoon.eot?srf3rx#iefix&quot;) format(&quot;embedded-opentype&quot;), url(&quot;../fonts/icomoon/icomoon.ttf?srf3rx&quot;) format(&quot;truetype&quot;), url(&quot;../fonts/icomoon/icomoon.woff?srf3rx&quot;) format(&quot;woff&quot;), url(&quot;../fonts/icomoon/icomoon.svg?srf3rx#icomoon&quot;) format(&quot;svg&quot;);
        '''  font-weight: normal;
        '''  font-style: normal;
        '''}
        '''/* =======================================================
        '''*
        '''* 	Template Style 
        '''*
        '''* ====== [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property style_css() As String
            Get
                Return ResourceManager.GetString("style.css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        '''&lt;html&gt;
        '''	&lt;head&gt;
        '''	&lt;meta charset=&quot;utf-8&quot;&gt;
        '''	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        '''	&lt;title&gt;cloud Lillith - InstaDL&lt;/title&gt;
        '''	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        '''	&lt;meta name=&quot;description&quot; content=&quot;cloud Lillith Platform InstaDL&quot; /&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot; /&gt;
        '''	&lt;meta name=&quot;author&quot; content=&quot;&quot; /&gt;
        '''
        '''	&lt;meta property=&quot;og:title&quot; content=&quot;&quot;/&gt;
        '''	&lt;meta property=&quot;og:image&quot; content=&quot;&quot;/&gt;
        '''	&lt;meta property=&quot;og:url&quot; content=&quot;&quot;/&gt;
        '''	&lt;meta property=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TopPart() As String
            Get
                Return ResourceManager.GetString("TopPart", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
